### ISSUE TITLE
SalsaJ using an old version of NomTam Fits (no fpack support?)

### ISSUE THREAD

**Issue by Fingel** [SalsaJ/SalsaJ#1]
Hello,

At LCOGT we provide data to our users as fpacked fits files. We have a number of users using SalsaJ. Currently, SalsaJ does not support reading fpacked images.

In looking through the SalsaJ source code, it looks like it uses NomTam Fits to read fits files. However, the version included is old, and while NomTam does support fpacked images, the version included in the SalsaJ source tree does not.

So my questions are:
1. Would it be possible to update the nomtam source tree in SalsaJ to the latest version so that user can open fpack'd files?
2. Why does SalsaJ include nomtam in it's source code directly instead of treating it as a dependency? (I fear the answer to this question might explain #1)

Thank you!

**Comment by SergeStinckwich** [comment]
There is not that much people using Salsa/J. Maybe this is better to use the mailing-list for such problem ?
